@echo off
set project=Simple Saturation Plugin
set build_path=C:\Users\conta\Documents\HISE\Hise Projects\Simple Saturation Plugin\Binaries
set msbuild="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MsBuild.exe"
set vs_args=/p:Configuration="Release" /verbosity:minimal
set PreferredToolArchitecture=x64
set VisualStudioVersion=15.0

"C:\Users\conta\Documents\HISE\HISE-develop\HISE-develop\tools\Projucer\Projucer.exe" --resave "%build_path%\AutogeneratedProject.jucer"

echo Compiling 64bit FX plugin %project% ...
set Platform=X64
%msbuild% "%build_path%\Builds\VisualStudio2017\%project%.sln" %vs_args%



pause
